# Generated by Django 5.0.3 on 2024-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('authorname', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pages', models.IntegerField(max_length=200)),
                ('coAuthor', models.CharField(max_length=200)),
                ('authorIntro', models.CharField(max_length=200)),
                ('bookIntro', models.CharField(max_length=200)),
                ('published', models.DateField(max_length=200)),
                ('reviewed', models.DateField(max_length=200)),
            ],
        ),
    ]
